-- Deploy dictybase:jbrowse to pg
-- requires: @dictychado-1.23

BEGIN;

create table jbrowse (
    jbrowse_id serial not null,
    name varchar(32) not null,
    configuration jsonb not null,
    primary key(jbrowse_id),
    unique (name)
);

COMMENT ON TABLE jbrowse IS 'A table to store the top level jbrowse configuration in json format. Multiple different instances
of jbrowse could be configured in this table';

COMMENT ON COLUMN jbrowse.name IS 'The name of the jbrowse project, required and should be unique. It is more
or less tied to one instance of jbrowse';

COMMENT ON COLUMN jbrowse.configuration IS 'The json.conf file in json format';

create table jbrowse_organism (
    jbrowse_organism_id serial not null,
    organism_id int not null,
    jbrowse_id int not null,
    foreign key (organism_id) references organism (organism_id) on delete cascade INITIALLY DEFERRED,
    foreign key (jbrowse_id) references jbrowse (jbrowse_id) on delete cascade INITIALLY DEFERRED,
    primary key (jbrowse_organism_id),
    unique (organism_id, jbrowse_id)
);

COMMENT ON TABLE jbrowse_organism IS 'A linking table between jbrowse configuration and organism(genome). It mimics 
the concept of jbrowse to have multiple organisms for each jbrowse configuration. The unique constraint gurantees 
one organism per jbrowse configuration whereas allows to have another instances in different configuration if needed.';

create table jbrowse_track (
    jbrowse_track_id serial not null,
    configuration jsonb not null,
    type_id int not null,
    jbrowse_organism_id int not null,
    foreign key (type_id) references cvterm (cvterm_id) on delete cascade INITIALLY DEFERRED,
    foreign key (jbrowse_organism_id) references jbrowse_organism (jbrowse_organism_id) on delete cascade INITIALLY DEFERRED,
    primary key (jbrowse_track_id)
);

COMMENT ON TABLE jbrowse_track IS 'A table to store all track configurations for an organism tied to a particular 
ontology(most SO) type.';

COMMENT ON COLUMN jbrowse_track.configuration IS 'Json configuration of every track as specified in trackList.json file in jbrowse. The entire trackList.json 
is not stored as it can be generated by combining each value for each organism.';

COMMENT ON COLUMN jbrowse_track.type_id IS 'Foreign key linked to the ontology, makes sure each track configuration has a defined 
and recognizable data type in the database';

COMMIT;
