-- Verify chado module mage


    SELECT pg_catalog.has_table_privilege('mageml','select');
SELECT pg_catalog.has_column_privilege('mageml', 'mageml_id', 'select');
SELECT pg_catalog.has_column_privilege('mageml', 'mage_package', 'select');
SELECT pg_catalog.has_column_privilege('mageml', 'mage_ml', 'select');
SELECT pg_catalog.has_table_privilege('magedocumentation','select');
SELECT pg_catalog.has_column_privilege('magedocumentation', 'magedocumentation_id', 'select');
SELECT pg_catalog.has_column_privilege('magedocumentation', 'mageml_id', 'select');
SELECT pg_catalog.has_column_privilege('magedocumentation', 'tableinfo_id', 'select');
SELECT pg_catalog.has_column_privilege('magedocumentation', 'row_id', 'select');
SELECT pg_catalog.has_column_privilege('magedocumentation', 'mageidentifier', 'select');
SELECT pg_catalog.has_table_privilege('protocol','select');
SELECT pg_catalog.has_column_privilege('protocol', 'protocol_id', 'select');
SELECT pg_catalog.has_column_privilege('protocol', 'type_id', 'select');
SELECT pg_catalog.has_column_privilege('protocol', 'pub_id', 'select');
SELECT pg_catalog.has_column_privilege('protocol', 'dbxref_id', 'select');
SELECT pg_catalog.has_column_privilege('protocol', 'name', 'select');
SELECT pg_catalog.has_column_privilege('protocol', 'uri', 'select');
SELECT pg_catalog.has_column_privilege('protocol', 'protocoldescription', 'select');
SELECT pg_catalog.has_column_privilege('protocol', 'hardwaredescription', 'select');
SELECT pg_catalog.has_column_privilege('protocol', 'softwaredescription', 'select');
SELECT pg_catalog.has_table_privilege('protocolparam','select');
SELECT pg_catalog.has_column_privilege('protocolparam', 'protocolparam_id', 'select');
SELECT pg_catalog.has_column_privilege('protocolparam', 'protocol_id', 'select');
SELECT pg_catalog.has_column_privilege('protocolparam', 'name', 'select');
SELECT pg_catalog.has_column_privilege('protocolparam', 'datatype_id', 'select');
SELECT pg_catalog.has_column_privilege('protocolparam', 'unittype_id', 'select');
SELECT pg_catalog.has_column_privilege('protocolparam', 'value', 'select');
SELECT pg_catalog.has_column_privilege('protocolparam', 'rank', 'select');
SELECT pg_catalog.has_table_privilege('channel','select');
SELECT pg_catalog.has_column_privilege('channel', 'channel_id', 'select');
SELECT pg_catalog.has_column_privilege('channel', 'name', 'select');
SELECT pg_catalog.has_column_privilege('channel', 'definition', 'select');
SELECT pg_catalog.has_table_privilege('arraydesign','select');
SELECT pg_catalog.has_column_privilege('arraydesign', 'arraydesign_id', 'select');
SELECT pg_catalog.has_column_privilege('arraydesign', 'manufacturer_id', 'select');
SELECT pg_catalog.has_column_privilege('arraydesign', 'platformtype_id', 'select');
SELECT pg_catalog.has_column_privilege('arraydesign', 'substratetype_id', 'select');
SELECT pg_catalog.has_column_privilege('arraydesign', 'protocol_id', 'select');
SELECT pg_catalog.has_column_privilege('arraydesign', 'dbxref_id', 'select');
SELECT pg_catalog.has_column_privilege('arraydesign', 'name', 'select');
SELECT pg_catalog.has_column_privilege('arraydesign', 'version', 'select');
SELECT pg_catalog.has_column_privilege('arraydesign', 'description', 'select');
SELECT pg_catalog.has_column_privilege('arraydesign', 'array_dimensions', 'select');
SELECT pg_catalog.has_column_privilege('arraydesign', 'element_dimensions', 'select');
SELECT pg_catalog.has_column_privilege('arraydesign', 'num_of_elements', 'select');
SELECT pg_catalog.has_column_privilege('arraydesign', 'num_array_columns', 'select');
SELECT pg_catalog.has_column_privilege('arraydesign', 'num_array_rows', 'select');
SELECT pg_catalog.has_column_privilege('arraydesign', 'num_grid_columns', 'select');
SELECT pg_catalog.has_column_privilege('arraydesign', 'num_grid_rows', 'select');
SELECT pg_catalog.has_column_privilege('arraydesign', 'num_sub_columns', 'select');
SELECT pg_catalog.has_column_privilege('arraydesign', 'num_sub_rows', 'select');
SELECT pg_catalog.has_table_privilege('arraydesignprop','select');
SELECT pg_catalog.has_column_privilege('arraydesignprop', 'arraydesignprop_id', 'select');
SELECT pg_catalog.has_column_privilege('arraydesignprop', 'arraydesign_id', 'select');
SELECT pg_catalog.has_column_privilege('arraydesignprop', 'type_id', 'select');
SELECT pg_catalog.has_column_privilege('arraydesignprop', 'value', 'select');
SELECT pg_catalog.has_column_privilege('arraydesignprop', 'rank', 'select');
SELECT pg_catalog.has_table_privilege('assay','select');
SELECT pg_catalog.has_column_privilege('assay', 'assay_id', 'select');
SELECT pg_catalog.has_column_privilege('assay', 'arraydesign_id', 'select');
SELECT pg_catalog.has_column_privilege('assay', 'protocol_id', 'select');
SELECT pg_catalog.has_column_privilege('assay', 'assaydate', 'select');
SELECT pg_catalog.has_column_privilege('assay', 'arrayidentifier', 'select');
SELECT pg_catalog.has_column_privilege('assay', 'arraybatchidentifier', 'select');
SELECT pg_catalog.has_column_privilege('assay', 'operator_id', 'select');
SELECT pg_catalog.has_column_privilege('assay', 'dbxref_id', 'select');
SELECT pg_catalog.has_column_privilege('assay', 'name', 'select');
SELECT pg_catalog.has_column_privilege('assay', 'description', 'select');
SELECT pg_catalog.has_table_privilege('assayprop','select');
SELECT pg_catalog.has_column_privilege('assayprop', 'assayprop_id', 'select');
SELECT pg_catalog.has_column_privilege('assayprop', 'assay_id', 'select');
SELECT pg_catalog.has_column_privilege('assayprop', 'type_id', 'select');
SELECT pg_catalog.has_column_privilege('assayprop', 'value', 'select');
SELECT pg_catalog.has_column_privilege('assayprop', 'rank', 'select');
SELECT pg_catalog.has_table_privilege('assay_project','select');
SELECT pg_catalog.has_column_privilege('assay_project', 'assay_project_id', 'select');
SELECT pg_catalog.has_column_privilege('assay_project', 'assay_id', 'select');
SELECT pg_catalog.has_column_privilege('assay_project', 'project_id', 'select');
SELECT pg_catalog.has_table_privilege('biomaterial','select');
SELECT pg_catalog.has_column_privilege('biomaterial', 'biomaterial_id', 'select');
SELECT pg_catalog.has_column_privilege('biomaterial', 'taxon_id', 'select');
SELECT pg_catalog.has_column_privilege('biomaterial', 'biosourceprovider_id', 'select');
SELECT pg_catalog.has_column_privilege('biomaterial', 'dbxref_id', 'select');
SELECT pg_catalog.has_column_privilege('biomaterial', 'name', 'select');
SELECT pg_catalog.has_column_privilege('biomaterial', 'description', 'select');
SELECT pg_catalog.has_table_privilege('biomaterial_relationship','select');
SELECT pg_catalog.has_column_privilege('biomaterial_relationship', 'biomaterial_relationship_id', 'select');
SELECT pg_catalog.has_column_privilege('biomaterial_relationship', 'subject_id', 'select');
SELECT pg_catalog.has_column_privilege('biomaterial_relationship', 'type_id', 'select');
SELECT pg_catalog.has_column_privilege('biomaterial_relationship', 'object_id', 'select');
SELECT pg_catalog.has_table_privilege('biomaterialprop','select');
SELECT pg_catalog.has_column_privilege('biomaterialprop', 'biomaterialprop_id', 'select');
SELECT pg_catalog.has_column_privilege('biomaterialprop', 'biomaterial_id', 'select');
SELECT pg_catalog.has_column_privilege('biomaterialprop', 'type_id', 'select');
SELECT pg_catalog.has_column_privilege('biomaterialprop', 'value', 'select');
SELECT pg_catalog.has_column_privilege('biomaterialprop', 'rank', 'select');
SELECT pg_catalog.has_table_privilege('biomaterial_dbxref','select');
SELECT pg_catalog.has_column_privilege('biomaterial_dbxref', 'biomaterial_dbxref_id', 'select');
SELECT pg_catalog.has_column_privilege('biomaterial_dbxref', 'biomaterial_id', 'select');
SELECT pg_catalog.has_column_privilege('biomaterial_dbxref', 'dbxref_id', 'select');
SELECT pg_catalog.has_table_privilege('treatment','select');
SELECT pg_catalog.has_column_privilege('treatment', 'treatment_id', 'select');
SELECT pg_catalog.has_column_privilege('treatment', 'rank', 'select');
SELECT pg_catalog.has_column_privilege('treatment', 'biomaterial_id', 'select');
SELECT pg_catalog.has_column_privilege('treatment', 'type_id', 'select');
SELECT pg_catalog.has_column_privilege('treatment', 'protocol_id', 'select');
SELECT pg_catalog.has_column_privilege('treatment', 'name', 'select');
SELECT pg_catalog.has_table_privilege('biomaterial_treatment','select');
SELECT pg_catalog.has_column_privilege('biomaterial_treatment', 'biomaterial_treatment_id', 'select');
SELECT pg_catalog.has_column_privilege('biomaterial_treatment', 'biomaterial_id', 'select');
SELECT pg_catalog.has_column_privilege('biomaterial_treatment', 'treatment_id', 'select');
SELECT pg_catalog.has_column_privilege('biomaterial_treatment', 'unittype_id', 'select');
SELECT pg_catalog.has_column_privilege('biomaterial_treatment', 'value', 'select');
SELECT pg_catalog.has_column_privilege('biomaterial_treatment', 'rank', 'select');
SELECT pg_catalog.has_table_privilege('assay_biomaterial','select');
SELECT pg_catalog.has_column_privilege('assay_biomaterial', 'assay_biomaterial_id', 'select');
SELECT pg_catalog.has_column_privilege('assay_biomaterial', 'assay_id', 'select');
SELECT pg_catalog.has_column_privilege('assay_biomaterial', 'biomaterial_id', 'select');
SELECT pg_catalog.has_column_privilege('assay_biomaterial', 'channel_id', 'select');
SELECT pg_catalog.has_column_privilege('assay_biomaterial', 'rank', 'select');
SELECT pg_catalog.has_table_privilege('acquisition','select');
SELECT pg_catalog.has_column_privilege('acquisition', 'acquisition_id', 'select');
SELECT pg_catalog.has_column_privilege('acquisition', 'assay_id', 'select');
SELECT pg_catalog.has_column_privilege('acquisition', 'protocol_id', 'select');
SELECT pg_catalog.has_column_privilege('acquisition', 'channel_id', 'select');
SELECT pg_catalog.has_column_privilege('acquisition', 'acquisitiondate', 'select');
SELECT pg_catalog.has_column_privilege('acquisition', 'name', 'select');
SELECT pg_catalog.has_column_privilege('acquisition', 'uri', 'select');
SELECT pg_catalog.has_table_privilege('acquisitionprop','select');
SELECT pg_catalog.has_column_privilege('acquisitionprop', 'acquisitionprop_id', 'select');
SELECT pg_catalog.has_column_privilege('acquisitionprop', 'acquisition_id', 'select');
SELECT pg_catalog.has_column_privilege('acquisitionprop', 'type_id', 'select');
SELECT pg_catalog.has_column_privilege('acquisitionprop', 'value', 'select');
SELECT pg_catalog.has_column_privilege('acquisitionprop', 'rank', 'select');
SELECT pg_catalog.has_table_privilege('acquisition_relationship','select');
SELECT pg_catalog.has_column_privilege('acquisition_relationship', 'acquisition_relationship_id', 'select');
SELECT pg_catalog.has_column_privilege('acquisition_relationship', 'subject_id', 'select');
SELECT pg_catalog.has_column_privilege('acquisition_relationship', 'type_id', 'select');
SELECT pg_catalog.has_column_privilege('acquisition_relationship', 'object_id', 'select');
SELECT pg_catalog.has_column_privilege('acquisition_relationship', 'value', 'select');
SELECT pg_catalog.has_column_privilege('acquisition_relationship', 'rank', 'select');
SELECT pg_catalog.has_table_privilege('quantification','select');
SELECT pg_catalog.has_column_privilege('quantification', 'quantification_id', 'select');
SELECT pg_catalog.has_column_privilege('quantification', 'acquisition_id', 'select');
SELECT pg_catalog.has_column_privilege('quantification', 'operator_id', 'select');
SELECT pg_catalog.has_column_privilege('quantification', 'protocol_id', 'select');
SELECT pg_catalog.has_column_privilege('quantification', 'analysis_id', 'select');
SELECT pg_catalog.has_column_privilege('quantification', 'quantificationdate', 'select');
SELECT pg_catalog.has_column_privilege('quantification', 'name', 'select');
SELECT pg_catalog.has_column_privilege('quantification', 'uri', 'select');
SELECT pg_catalog.has_table_privilege('quantificationprop','select');
SELECT pg_catalog.has_column_privilege('quantificationprop', 'quantificationprop_id', 'select');
SELECT pg_catalog.has_column_privilege('quantificationprop', 'quantification_id', 'select');
SELECT pg_catalog.has_column_privilege('quantificationprop', 'type_id', 'select');
SELECT pg_catalog.has_column_privilege('quantificationprop', 'value', 'select');
SELECT pg_catalog.has_column_privilege('quantificationprop', 'rank', 'select');
SELECT pg_catalog.has_table_privilege('quantification_relationship','select');
SELECT pg_catalog.has_column_privilege('quantification_relationship', 'quantification_relationship_id', 'select');
SELECT pg_catalog.has_column_privilege('quantification_relationship', 'subject_id', 'select');
SELECT pg_catalog.has_column_privilege('quantification_relationship', 'type_id', 'select');
SELECT pg_catalog.has_column_privilege('quantification_relationship', 'object_id', 'select');
SELECT pg_catalog.has_table_privilege('control','select');
SELECT pg_catalog.has_column_privilege('control', 'control_id', 'select');
SELECT pg_catalog.has_column_privilege('control', 'type_id', 'select');
SELECT pg_catalog.has_column_privilege('control', 'assay_id', 'select');
SELECT pg_catalog.has_column_privilege('control', 'tableinfo_id', 'select');
SELECT pg_catalog.has_column_privilege('control', 'row_id', 'select');
SELECT pg_catalog.has_column_privilege('control', 'name', 'select');
SELECT pg_catalog.has_column_privilege('control', 'value', 'select');
SELECT pg_catalog.has_column_privilege('control', 'rank', 'select');
SELECT pg_catalog.has_table_privilege('element','select');
SELECT pg_catalog.has_column_privilege('element', 'element_id', 'select');
SELECT pg_catalog.has_column_privilege('element', 'feature_id', 'select');
SELECT pg_catalog.has_column_privilege('element', 'arraydesign_id', 'select');
SELECT pg_catalog.has_column_privilege('element', 'type_id', 'select');
SELECT pg_catalog.has_column_privilege('element', 'dbxref_id', 'select');
SELECT pg_catalog.has_table_privilege('elementresult','select');
SELECT pg_catalog.has_column_privilege('elementresult', 'elementresult_id', 'select');
SELECT pg_catalog.has_column_privilege('elementresult', 'element_id', 'select');
SELECT pg_catalog.has_column_privilege('elementresult', 'quantification_id', 'select');
SELECT pg_catalog.has_column_privilege('elementresult', 'signal', 'select');
SELECT pg_catalog.has_table_privilege('element_relationship','select');
SELECT pg_catalog.has_column_privilege('element_relationship', 'element_relationship_id', 'select');
SELECT pg_catalog.has_column_privilege('element_relationship', 'subject_id', 'select');
SELECT pg_catalog.has_column_privilege('element_relationship', 'type_id', 'select');
SELECT pg_catalog.has_column_privilege('element_relationship', 'object_id', 'select');
SELECT pg_catalog.has_column_privilege('element_relationship', 'value', 'select');
SELECT pg_catalog.has_column_privilege('element_relationship', 'rank', 'select');
SELECT pg_catalog.has_table_privilege('elementresult_relationship','select');
SELECT pg_catalog.has_column_privilege('elementresult_relationship', 'elementresult_relationship_id', 'select');
SELECT pg_catalog.has_column_privilege('elementresult_relationship', 'subject_id', 'select');
SELECT pg_catalog.has_column_privilege('elementresult_relationship', 'type_id', 'select');
SELECT pg_catalog.has_column_privilege('elementresult_relationship', 'object_id', 'select');
SELECT pg_catalog.has_column_privilege('elementresult_relationship', 'value', 'select');
SELECT pg_catalog.has_column_privilege('elementresult_relationship', 'rank', 'select');
SELECT pg_catalog.has_table_privilege('study','select');
SELECT pg_catalog.has_column_privilege('study', 'study_id', 'select');
SELECT pg_catalog.has_column_privilege('study', 'contact_id', 'select');
SELECT pg_catalog.has_column_privilege('study', 'pub_id', 'select');
SELECT pg_catalog.has_column_privilege('study', 'dbxref_id', 'select');
SELECT pg_catalog.has_column_privilege('study', 'name', 'select');
SELECT pg_catalog.has_column_privilege('study', 'description', 'select');
SELECT pg_catalog.has_table_privilege('study_assay','select');
SELECT pg_catalog.has_column_privilege('study_assay', 'study_assay_id', 'select');
SELECT pg_catalog.has_column_privilege('study_assay', 'study_id', 'select');
SELECT pg_catalog.has_column_privilege('study_assay', 'assay_id', 'select');
SELECT pg_catalog.has_table_privilege('studydesign','select');
SELECT pg_catalog.has_column_privilege('studydesign', 'studydesign_id', 'select');
SELECT pg_catalog.has_column_privilege('studydesign', 'study_id', 'select');
SELECT pg_catalog.has_column_privilege('studydesign', 'description', 'select');
SELECT pg_catalog.has_table_privilege('studydesignprop','select');
SELECT pg_catalog.has_column_privilege('studydesignprop', 'studydesignprop_id', 'select');
SELECT pg_catalog.has_column_privilege('studydesignprop', 'studydesign_id', 'select');
SELECT pg_catalog.has_column_privilege('studydesignprop', 'type_id', 'select');
SELECT pg_catalog.has_column_privilege('studydesignprop', 'value', 'select');
SELECT pg_catalog.has_column_privilege('studydesignprop', 'rank', 'select');
SELECT pg_catalog.has_table_privilege('studyfactor','select');
SELECT pg_catalog.has_column_privilege('studyfactor', 'studyfactor_id', 'select');
SELECT pg_catalog.has_column_privilege('studyfactor', 'studydesign_id', 'select');
SELECT pg_catalog.has_column_privilege('studyfactor', 'type_id', 'select');
SELECT pg_catalog.has_column_privilege('studyfactor', 'name', 'select');
SELECT pg_catalog.has_column_privilege('studyfactor', 'description', 'select');
SELECT pg_catalog.has_table_privilege('studyfactorvalue','select');
SELECT pg_catalog.has_column_privilege('studyfactorvalue', 'studyfactorvalue_id', 'select');
SELECT pg_catalog.has_column_privilege('studyfactorvalue', 'studyfactor_id', 'select');
SELECT pg_catalog.has_column_privilege('studyfactorvalue', 'assay_id', 'select');
SELECT pg_catalog.has_column_privilege('studyfactorvalue', 'factorvalue', 'select');
SELECT pg_catalog.has_column_privilege('studyfactorvalue', 'name', 'select');
SELECT pg_catalog.has_column_privilege('studyfactorvalue', 'rank', 'select');
SELECT pg_catalog.has_table_privilege('studyprop','select');
SELECT pg_catalog.has_column_privilege('studyprop', 'studyprop_id', 'select');
SELECT pg_catalog.has_column_privilege('studyprop', 'study_id', 'select');
SELECT pg_catalog.has_column_privilege('studyprop', 'type_id', 'select');
SELECT pg_catalog.has_column_privilege('studyprop', 'value', 'select');
SELECT pg_catalog.has_column_privilege('studyprop', 'rank', 'select');
SELECT pg_catalog.has_table_privilege('studyprop_feature','select');
SELECT pg_catalog.has_column_privilege('studyprop_feature', 'studyprop_feature_id', 'select');
SELECT pg_catalog.has_column_privilege('studyprop_feature', 'studyprop_id', 'select');
SELECT pg_catalog.has_column_privilege('studyprop_feature', 'feature_id', 'select');
SELECT pg_catalog.has_column_privilege('studyprop_feature', 'type_id', 'select');



