-- Verify chado module natural-diversity


    BEGIN;
    SELECT pg_catalog.has_table_privilege('nd_geolocation','select');
SELECT pg_catalog.has_column_privilege('nd_geolocation', 'nd_geolocation_id', 'select');
SELECT pg_catalog.has_column_privilege('nd_geolocation', 'description', 'select');
SELECT pg_catalog.has_column_privilege('nd_geolocation', 'latitude', 'select');
SELECT pg_catalog.has_column_privilege('nd_geolocation', 'longitude', 'select');
SELECT pg_catalog.has_column_privilege('nd_geolocation', 'geodetic_datum', 'select');
SELECT pg_catalog.has_column_privilege('nd_geolocation', 'altitude', 'select');
SELECT pg_catalog.has_table_privilege('nd_experiment','select');
SELECT pg_catalog.has_column_privilege('nd_experiment', 'nd_experiment_id', 'select');
SELECT pg_catalog.has_column_privilege('nd_experiment', 'nd_geolocation_id', 'select');
SELECT pg_catalog.has_column_privilege('nd_experiment', 'type_id', 'select');
SELECT pg_catalog.has_table_privilege('nd_experiment_project','select');
SELECT pg_catalog.has_column_privilege('nd_experiment_project', 'nd_experiment_project_id', 'select');
SELECT pg_catalog.has_column_privilege('nd_experiment_project', 'project_id', 'select');
SELECT pg_catalog.has_column_privilege('nd_experiment_project', 'nd_experiment_id', 'select');
SELECT pg_catalog.has_table_privilege('nd_experimentprop','select');
SELECT pg_catalog.has_column_privilege('nd_experimentprop', 'nd_experimentprop_id', 'select');
SELECT pg_catalog.has_column_privilege('nd_experimentprop', 'nd_experiment_id', 'select');
SELECT pg_catalog.has_column_privilege('nd_experimentprop', 'type_id', 'select');
SELECT pg_catalog.has_column_privilege('nd_experimentprop', 'value', 'select');
SELECT pg_catalog.has_column_privilege('nd_experimentprop', 'rank', 'select');
SELECT pg_catalog.has_table_privilege('nd_experiment_pub','select');
SELECT pg_catalog.has_column_privilege('nd_experiment_pub', 'nd_experiment_pub_id', 'select');
SELECT pg_catalog.has_column_privilege('nd_experiment_pub', 'nd_experiment_id', 'select');
SELECT pg_catalog.has_column_privilege('nd_experiment_pub', 'pub_id', 'select');
SELECT pg_catalog.has_table_privilege('nd_geolocationprop','select');
SELECT pg_catalog.has_column_privilege('nd_geolocationprop', 'nd_geolocationprop_id', 'select');
SELECT pg_catalog.has_column_privilege('nd_geolocationprop', 'nd_geolocation_id', 'select');
SELECT pg_catalog.has_column_privilege('nd_geolocationprop', 'type_id', 'select');
SELECT pg_catalog.has_column_privilege('nd_geolocationprop', 'value', 'select');
SELECT pg_catalog.has_column_privilege('nd_geolocationprop', 'rank', 'select');
SELECT pg_catalog.has_table_privilege('nd_protocol','select');
SELECT pg_catalog.has_column_privilege('nd_protocol', 'nd_protocol_id', 'select');
SELECT pg_catalog.has_column_privilege('nd_protocol', 'name', 'select');
SELECT pg_catalog.has_column_privilege('nd_protocol', 'type_id', 'select');
SELECT pg_catalog.has_table_privilege('nd_reagent','select');
SELECT pg_catalog.has_column_privilege('nd_reagent', 'nd_reagent_id', 'select');
SELECT pg_catalog.has_column_privilege('nd_reagent', 'name', 'select');
SELECT pg_catalog.has_column_privilege('nd_reagent', 'type_id', 'select');
SELECT pg_catalog.has_column_privilege('nd_reagent', 'feature_id', 'select');
SELECT pg_catalog.has_table_privilege('nd_protocol_reagent','select');
SELECT pg_catalog.has_column_privilege('nd_protocol_reagent', 'nd_protocol_reagent_id', 'select');
SELECT pg_catalog.has_column_privilege('nd_protocol_reagent', 'nd_protocol_id', 'select');
SELECT pg_catalog.has_column_privilege('nd_protocol_reagent', 'reagent_id', 'select');
SELECT pg_catalog.has_column_privilege('nd_protocol_reagent', 'type_id', 'select');
SELECT pg_catalog.has_table_privilege('nd_protocolprop','select');
SELECT pg_catalog.has_column_privilege('nd_protocolprop', 'nd_protocolprop_id', 'select');
SELECT pg_catalog.has_column_privilege('nd_protocolprop', 'nd_protocol_id', 'select');
SELECT pg_catalog.has_column_privilege('nd_protocolprop', 'type_id', 'select');
SELECT pg_catalog.has_column_privilege('nd_protocolprop', 'value', 'select');
SELECT pg_catalog.has_column_privilege('nd_protocolprop', 'rank', 'select');
SELECT pg_catalog.has_table_privilege('nd_experiment_stock','select');
SELECT pg_catalog.has_column_privilege('nd_experiment_stock', 'nd_experiment_stock_id', 'select');
SELECT pg_catalog.has_column_privilege('nd_experiment_stock', 'nd_experiment_id', 'select');
SELECT pg_catalog.has_column_privilege('nd_experiment_stock', 'stock_id', 'select');
SELECT pg_catalog.has_column_privilege('nd_experiment_stock', 'type_id', 'select');
SELECT pg_catalog.has_table_privilege('nd_experiment_protocol','select');
SELECT pg_catalog.has_column_privilege('nd_experiment_protocol', 'nd_experiment_protocol_id', 'select');
SELECT pg_catalog.has_column_privilege('nd_experiment_protocol', 'nd_experiment_id', 'select');
SELECT pg_catalog.has_column_privilege('nd_experiment_protocol', 'nd_protocol_id', 'select');
SELECT pg_catalog.has_table_privilege('nd_experiment_phenotype','select');
SELECT pg_catalog.has_column_privilege('nd_experiment_phenotype', 'nd_experiment_phenotype_id', 'select');
SELECT pg_catalog.has_column_privilege('nd_experiment_phenotype', 'nd_experiment_id', 'select');
SELECT pg_catalog.has_column_privilege('nd_experiment_phenotype', 'phenotype_id', 'select');
SELECT pg_catalog.has_table_privilege('nd_experiment_genotype','select');
SELECT pg_catalog.has_column_privilege('nd_experiment_genotype', 'nd_experiment_genotype_id', 'select');
SELECT pg_catalog.has_column_privilege('nd_experiment_genotype', 'nd_experiment_id', 'select');
SELECT pg_catalog.has_column_privilege('nd_experiment_genotype', 'genotype_id', 'select');
SELECT pg_catalog.has_table_privilege('nd_reagent_relationship','select');
SELECT pg_catalog.has_column_privilege('nd_reagent_relationship', 'nd_reagent_relationship_id', 'select');
SELECT pg_catalog.has_column_privilege('nd_reagent_relationship', 'subject_reagent_id', 'select');
SELECT pg_catalog.has_column_privilege('nd_reagent_relationship', 'object_reagent_id', 'select');
SELECT pg_catalog.has_column_privilege('nd_reagent_relationship', 'type_id', 'select');
SELECT pg_catalog.has_table_privilege('nd_reagentprop','select');
SELECT pg_catalog.has_column_privilege('nd_reagentprop', 'nd_reagentprop_id', 'select');
SELECT pg_catalog.has_column_privilege('nd_reagentprop', 'nd_reagent_id', 'select');
SELECT pg_catalog.has_column_privilege('nd_reagentprop', 'type_id', 'select');
SELECT pg_catalog.has_column_privilege('nd_reagentprop', 'value', 'select');
SELECT pg_catalog.has_column_privilege('nd_reagentprop', 'rank', 'select');
SELECT pg_catalog.has_table_privilege('nd_experiment_stockprop','select');
SELECT pg_catalog.has_column_privilege('nd_experiment_stockprop', 'nd_experiment_stockprop_id', 'select');
SELECT pg_catalog.has_column_privilege('nd_experiment_stockprop', 'nd_experiment_stock_id', 'select');
SELECT pg_catalog.has_column_privilege('nd_experiment_stockprop', 'type_id', 'select');
SELECT pg_catalog.has_column_privilege('nd_experiment_stockprop', 'value', 'select');
SELECT pg_catalog.has_column_privilege('nd_experiment_stockprop', 'rank', 'select');
SELECT pg_catalog.has_table_privilege('nd_experiment_stock_dbxref','select');
SELECT pg_catalog.has_column_privilege('nd_experiment_stock_dbxref', 'nd_experiment_stock_dbxref_id', 'select');
SELECT pg_catalog.has_column_privilege('nd_experiment_stock_dbxref', 'nd_experiment_stock_id', 'select');
SELECT pg_catalog.has_column_privilege('nd_experiment_stock_dbxref', 'dbxref_id', 'select');
SELECT pg_catalog.has_table_privilege('nd_experiment_dbxref','select');
SELECT pg_catalog.has_column_privilege('nd_experiment_dbxref', 'nd_experiment_dbxref_id', 'select');
SELECT pg_catalog.has_column_privilege('nd_experiment_dbxref', 'nd_experiment_id', 'select');
SELECT pg_catalog.has_column_privilege('nd_experiment_dbxref', 'dbxref_id', 'select');
SELECT pg_catalog.has_table_privilege('nd_experiment_contact','select');
SELECT pg_catalog.has_column_privilege('nd_experiment_contact', 'nd_experiment_contact_id', 'select');
SELECT pg_catalog.has_column_privilege('nd_experiment_contact', 'nd_experiment_id', 'select');
SELECT pg_catalog.has_column_privilege('nd_experiment_contact', 'contact_id', 'select');

    ROLLBACK;


