site_name : Chado Sqitch Documentation
docs_dir: sources
repo_url: https://github.com/dictyBase/Chado-Sqitch
pages :
    - ['index.md', 'About']
    - ['use_cases/install_schema_only.md', 'Use Cases', 'Install chado schema']
    - ['use_cases/install_schema_manage.md', 'Use Cases', 'Install and manage chado schema']
